import { useEffect,useMemo,useRef,useState } from 'react'
import type { Membership, ProductOverview } from '../lib/types'
import { buildIndex,codesFromOcr,documentRows,parseCents,priceCandidates,safeCsv,type Box,type OcrResult } from './domain'
import { OcrEngine } from './engines'
import { prepareImage,type PreparedImage } from './media'
import { discardDraft,draftEvents,flushDrafts,listDrafts,queueDraft,retryDraft,type CaptureDraft } from './offline'
import SmartScanPane from './SmartScanPane'
import './capture.css'

type Props={products:ProductOverview[];membership:Membership;owner:string;onSaved:(message:string)=>void;onError:(message:string)=>void}
export default function CaptureCenter({products,membership,owner,onSaved,onError}:Props){
  const [mode,setMode]=useState<'smart'|'price'|'document'>('smart'),[code,setCode]=useState(''),[price,setPrice]=useState(''),[reviewed,setReviewed]=useState(false),[engineName,setEngineName]=useState<'paddle'|'tesseract'>('paddle')
  const [prepared,setPrepared]=useState<PreparedImage|null>(null),[preview,setPreview]=useState(''),[result,setResult]=useState<OcrResult|null>(null),[working,setWorking]=useState(false),[status,setStatus]=useState(''),[error,setError]=useState(''),[saving,setSaving]=useState(false),[drafts,setDrafts]=useState<CaptureDraft[]>([]),[crop,setCrop]=useState<Box|null>(null),[cropEnabled,setCropEnabled]=useState(false),[filename,setFilename]=useState(''),[files,setFiles]=useState<File[]>([])
  const ocr=useRef<OcrEngine|null>(null),generation=useRef(0),cropStart=useRef<{x:number;y:number}|null>(null),mounted=useRef(true),busySave=useRef(false)
  const lookup=useMemo(()=>buildIndex(products),[products]),matches=lookup(code),product=matches.length===1?matches[0]:null
  const candidates=useMemo(()=>result?priceCandidates(result):[],[result]),rows=useMemo(()=>result?documentRows(result,lookup):[],[result,lookup])
  async function refreshDrafts(){try{const d=await listDrafts(owner,membership.store_id);if(mounted.current)setDrafts(d)}catch{if(mounted.current)setError('Η τοπική αποθήκευση δεν είναι διαθέσιμη. Οι καταγραφές δεν μπορούν να μπουν σε ουρά.')}}
  async function sync(){try{const count=await flushDrafts(owner,membership.store_id);if(count&&mounted.current)onSaved(`Συγχρονίστηκαν ${count} καταγραφές.`)}catch(e){if(mounted.current)setError(e instanceof Error?e.message:'Ο συγχρονισμός απέτυχε.')}}
  useEffect(()=>{
    mounted.current=true;void refreshDrafts();void sync()
    const update=()=>void refreshDrafts(),online=()=>void sync(),interval=setInterval(()=>void sync(),30000)
    draftEvents.addEventListener('change',update);window.addEventListener('online',online)
    return()=>{mounted.current=false;generation.current++;ocr.current?.cancel();ocr.current=null;clearInterval(interval);draftEvents.removeEventListener('change',update);window.removeEventListener('online',online)}
  },[owner,membership.store_id])
  useEffect(()=>{if(!prepared){setPreview('');return}const url=URL.createObjectURL(prepared.blob);setPreview(url);return()=>URL.revokeObjectURL(url)},[prepared])
  function invalidate(){setResult(null);setReviewed(false);setCrop(null);setCropEnabled(false);setError('')}
  function cancel(){generation.current++;ocr.current?.cancel();ocr.current=null;setWorking(false);setStatus('Η εργασία ακυρώθηκε. Δεν αποθηκεύτηκε τιμή.')}
  // Invalidate stale results, but retain an idle worker and its loaded models.
  // Cancellation of active inference, engine switches and unmount still release it.
  function nextCaptureJob(){generation.current++;if(working){ocr.current?.cancel();ocr.current=null}setWorking(false);cropStart.current=null}
  function changeMode(next:typeof mode){nextCaptureJob();setMode(next);invalidate();setPrepared(null);setPrice('');setCode('');setFiles([]);setFilename('');setStatus('')}
  async function selectFile(file:File){nextCaptureJob();invalidate();setPrepared(null);setFilename(file.name);setStatus('Προετοιμασία εικόνας…');setWorking(true);const gen=generation.current
    try{const p=await prepareImage(file);if(gen===generation.current){setPrepared(p);setStatus('Εικόνα έτοιμη. Περιόρισε την περιοχή πριν την ανάγνωση.')}}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:'Η εικόνα δεν διαβάζεται.')}finally{if(gen===generation.current)setWorking(false)}
  }
  async function transform(rotate=false){if(!prepared)return;invalidate();setWorking(true);const gen=generation.current
    try{const p=await prepareImage(prepared.blob,rotate?undefined:crop??undefined,rotate?90:0);if(gen===generation.current)setPrepared(p)}catch(e){if(gen===generation.current)setError(e instanceof Error?e.message:'Η περικοπή απέτυχε.')}finally{if(gen===generation.current)setWorking(false)}
  }
  async function recognize(){if(!prepared||working)return;invalidate();setWorking(true);setStatus('Προετοιμασία OCR…');const gen=generation.current,started=performance.now()
    try{ocr.current??=new OcrEngine();const r=await ocr.current.recognize(prepared.blob,engineName,mode==='document',s=>{if(gen===generation.current)setStatus(s)})
      if(gen!==generation.current)return;setResult(r);const codes=codesFromOcr(r,lookup);if(codes.length===1)setCode(codes[0]);else setCode('')
      const ps=[...new Set(priceCandidates(r).filter(p=>!p.unitPrice).map(p=>p.cents))];setPrice(ps.length===1?(ps[0]/100).toFixed(2):'')
      setStatus(`Η ανάγνωση ολοκληρώθηκε σε ${((performance.now()-started)/1000).toFixed(1)} s. Απαιτείται δικός σου έλεγχος.`)
    }catch(e){if(gen===generation.current)setError((e instanceof Error?e.message:'Αποτυχία OCR.')+' Μπορείς να δοκιμάσεις το εναλλακτικό OCR ή να συμπληρώσεις χειροκίνητα.')}
    finally{if(gen===generation.current)setWorking(false)}
  }
  async function save(){
    if(busySave.current||!reviewed||!product)return
    const cents=parseCents(price);if(cents===null){setError('Μη έγκυρη τιμή. Έως δύο δεκαδικά.');return}
    if(!product.unit){setError('Δεν έχει οριστεί μονάδα στο προϊόν. Χρειάζεται έλεγχος καταλόγου.');return}
    busySave.current=true;setSaving(true);setError('')
    try{const draft:CaptureDraft={id:crypto.randomUUID(),owner,store:membership.store_id,product:product.product_id,code:product.internal_code,cents,unit:product.unit,observedAt:new Date().toISOString(),created:Date.now(),attempts:0,error:'',retryAt:0,state:'pending',image:prepared?.blob??null,
      metadata:{engine:result?.engine??'manual',model:result?.engine??null,elapsed_ms:result?Math.round(result.elapsedMs):null,sha256:prepared?.sha256??null,source_file:filename||null,reviewed:true,reviewed_at:new Date().toISOString(),ocr_suggested_codes:result?codesFromOcr(result,lookup):[],ocr_prices:candidates.map(p=>({cents:p.cents,score:p.line.score,box:p.line.box,unit_price:p.unitPrice})),quality_warnings:prepared?.warnings??[],raw_text:result?.lines.map(l=>l.text).join('\n').slice(0,24000)??null}}
      await queueDraft(draft);setReviewed(false);setPrice('');setResult(null);setPrepared(null);setFilename('');setStatus('Αποθηκεύτηκε στη συσκευή. Η ουρά δείχνει την κατάσταση συγχρονισμού.');void sync()
    }catch(e){setError(e instanceof Error?e.message:'Η αποθήκευση απέτυχε. Κράτησε τη φωτογραφία και δοκίμασε ξανά.')}
    finally{busySave.current=false;setSaving(false)}
  }
  function exportRows(){const csv=safeCsv([['Κωδικός','Περιγραφή OCR','Μονάδα OCR','Τιμή OCR','Σειρά OCR','Αριθμός OCR','Κατάσταση'],...rows.map(r=>[r.code,r.description,r.unit,r.price,r.row,r.number,'ΜΗ ΕΠΙΒΕΒΑΙΩΜΕΝΟ'])]);download(csv,'leaksy-document-review.csv','text/csv;charset=utf-8')}
  function download(text:string,name:string,type='application/json'){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  const money=(cents:number)=>new Intl.NumberFormat('el-GR',{style:'currency',currency:'EUR'}).format(cents/100)
  const cursorPoint=(e:React.PointerEvent<HTMLDivElement>)=>{const rect=e.currentTarget.getBoundingClientRect();return{x:Math.max(0,Math.min(prepared!.width,(e.clientX-rect.left)/rect.width*prepared!.width)),y:Math.max(0,Math.min(prepared!.height,(e.clientY-rect.top)/rect.height*prepared!.height))}}
  return <div className="capture-center">
    <div className="capture-tabs" role="group" aria-label="Λειτουργία σάρωσης">{([['smart','Smart Scan'],['price','Μεμονωμένο OCR'],['document','Σελίδα Α4']] as const).map(([key,label])=><button key={key} className={`wk-button ${mode===key?'primary':''}`} aria-pressed={mode===key} onClick={()=>changeMode(key)}>{label}</button>)}</div>
    {mode==='smart'?<SmartScanPane products={products} membership={membership} owner={owner} onSaved={onSaved} onError={onError}/>:<section className="capture-pane"><div className="capture-heading"><h2>{mode==='price'?'Η σωστή τιμή, στο σωστό προϊόν.':'Ανάγνωση κατάστασης Α4.'}</h2><p>{mode==='price'?'Φωτογράφισε μόνο μία ετικέτα. Ποτέ αυτόματη αποθήκευση από OCR.':'Οι γραμμές είναι προσχέδιο. Τα ✓ και οι χειρόγραφες μετρήσεις δεν γίνονται τιμές ή ποσότητες.'}</p></div>
      <div className="capture-actions"><label className="wk-button primary">Φωτογραφία<input className="sr-only" type="file" aria-label="Φωτογραφία για OCR" accept="image/*" capture="environment" disabled={working} onChange={e=>{const f=e.target.files?.[0];if(f)void selectFile(f);e.target.value=''}}/></label><label className="wk-button">Από αρχεία<input className="sr-only" type="file" multiple={mode==='document'} aria-label="Επιλογή αρχείων OCR" accept="image/*" disabled={working} onChange={e=>{const selected=[...(e.target.files??[])];if(selected.length>20){setError('Διάλεξε έως 20 φωτογραφίες ανά παρτίδα.');return}setFiles(selected.slice(1));if(selected[0])void selectFile(selected[0]);e.target.value=''}}/></label><label className="capture-engine">Μηχανή<select aria-label="Μηχανή OCR" value={engineName} disabled={working} onChange={e=>{cancel();setEngineName(e.target.value as typeof engineName);invalidate()}}><option value="paddle">PaddleOCR · Ελληνικά</option><option value="tesseract">Tesseract · εναλλακτικό</option></select></label></div>
      {prepared&&<><div className={`capture-preview ${cropEnabled?'is-cropping':''}`} onPointerDown={e=>{if(working||!cropEnabled)return;cropStart.current=cursorPoint(e);e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(!cropEnabled||!cropStart.current||working)return;const p=cursorPoint(e),s=cropStart.current;setCrop({x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),width:Math.abs(p.x-s.x),height:Math.abs(p.y-s.y)})}} onPointerUp={()=>{cropStart.current=null}} onPointerCancel={()=>{cropStart.current=null}}><img src={preview} alt="Φωτογραφία προς έλεγχο" draggable={false}/>{crop&&<span className="capture-crop" style={{left:`${crop.x/prepared.width*100}%`,top:`${crop.y/prepared.height*100}%`,width:`${crop.width/prepared.width*100}%`,height:`${crop.height/prepared.height*100}%`}}/>}</div><div className="capture-actions"><button className="wk-button" aria-pressed={cropEnabled} disabled={working} onClick={()=>{setCropEnabled(v=>!v);setCrop(null);cropStart.current=null}}>Επιλογή περικοπής</button><button className="wk-button" disabled={!crop||working} onClick={()=>void transform()}>Περικοπή επιλογής</button><button className="wk-button" disabled={working} onClick={()=>void transform(true)}>Περιστροφή 90°</button><button className="wk-button primary" disabled={working} onClick={()=>void recognize()}>Ανάγνωση OCR</button>{working&&<button className="wk-button" onClick={cancel}>Ακύρωση</button>}</div><p className="capture-caption">Για περικοπή πάτησε «Επιλογή περικοπής» και σύρε στην εικόνα. Διαφορετικά, σύρε κανονικά για κύλιση της σελίδας. Τα μοντέλα φορτώνονται τοπικά την πρώτη φορά· δεν αποστέλλεται εικόνα σε πάροχο OCR.</p>{prepared.warnings.map(w=><p className="capture-warning" key={w}>{w}</p>)}</>}
      {status&&<p role="status" className="capture-status">{working&&<span className="capture-spinner"/>}{status}</p>}
      {error&&<p role="alert" className="capture-warning">{error}</p>}
      {mode==='price'&&<div className="capture-review"><h3>Επιβεβαίωση καταγραφής</h3><div className="capture-form-grid"><label className="capture-field">Κωδικός είδους<input aria-label="Κωδικός επιβεβαίωσης" inputMode="numeric" value={code} onChange={e=>{setCode(e.target.value);setReviewed(false)}}/></label><label className="capture-field">Τιμή ραφιού (€)<input aria-label="Τιμή επιβεβαίωσης" inputMode="decimal" value={price} onChange={e=>{setPrice(e.target.value);setReviewed(false)}}/></label></div>
        {!!candidates.length&&<div className="capture-candidates"><span>Αναγνώσεις OCR, όχι βεβαιωμένες τιμές:</span>{candidates.map((p,i)=><button className="wk-button" key={i} onClick={()=>{setPrice((p.cents/100).toFixed(2));setReviewed(false)}}>{money(p.cents)}{p.unitPrice?' / μονάδα':''} · {p.line.score===null?'χωρίς score':`score ${Math.round(p.line.score*100)}`}</button>)}</div>}
        {product?<div className="capture-product"><strong>{product.description}</strong><span>{product.internal_code} · Μονάδα: {product.unit||'ΜΗ ΟΡΙΣΜΕΝΗ'} · Κατάλογος: {product.catalog_price===null?'—':money(Math.round(product.catalog_price*100))}</span></div>:code&&<p className="capture-warning">{matches.length>1?'Διπλή αντιστοίχιση κωδικού. Απαιτείται διόρθωση καταλόγου.':'Δεν υπάρχει ακριβής, μοναδική αντιστοίχιση στον κατάλογο.'}</p>}
        {product?.unit!=='Τεμάχιο'&&product&&<p className="capture-warning">Έλεγξε ιδιαίτερα τη βάση τιμής: {product.unit||'άγνωστη μονάδα'}. Δεν γίνεται μετατροπή €/kg σε €/τεμάχιο.</p>}
        <label className="capture-check"><input type="checkbox" checked={reviewed} onChange={e=>setReviewed(e.target.checked)} disabled={!product||parseCents(price)===null}/>Έλεγξα προϊόν, τιμή και μονάδα στη φωτογραφία ή στο ράφι.</label><button className="wk-button primary" disabled={saving||working||!reviewed||!product||parseCents(price)===null} onClick={()=>void save()}>{saving?'Αποθήκευση…':'Επιβεβαίωση και αποθήκευση'}</button><p className="capture-caption">Η φωτογραφία αποθηκεύεται ως ιδιωτικό τεκμήριο μαζί με τη δική σου επιβεβαίωση. Εκτός σύνδεσης παραμένει στη συσκευή μέχρι τον συγχρονισμό.</p>
      </div>}
      {mode==='document'&&result&&<div className="capture-review"><h3>{rows.length} γραμμές προς έλεγχο</h3><p>Η εισαγωγή στον κύριο κατάλογο δεν είναι αυτόματη. Οι στήλες που δεν διαβάζονται μένουν κενές.</p><button className="wk-button" disabled={!rows.length} onClick={exportRows}>Εξαγωγή προσχεδίου CSV</button><div className="capture-doc-rows">{rows.map((r,i)=><div key={i}><code>{r.code}</code><span>{r.description}</span><b>{r.price||'Τιμή ασαφής'}</b><small>{r.known?'Υπάρχει στη βάση':'Νέος / μη αντιστοιχισμένος'} · {r.unit} · Σειρά {r.row||'—'} / {r.number||'—'}</small></div>)}</div></div>}
      {result&&<details><summary>Κείμενο και προέλευση OCR</summary><p>{result.engine} · {(result.elapsedMs/1000).toFixed(1)} s</p><pre className="capture-raw">{result.lines.map(l=>l.text).join('\n')}</pre></details>}
      {!!files.length&&<button className="wk-button" disabled={working} onClick={()=>{const f=files[0];setFiles(files.slice(1));void selectFile(f)}}>Επόμενη φωτογραφία ({files.length}) · εξήγαγε πρώτα το προσχέδιο</button>}
    </section>}
    <section className="capture-pane capture-outbox"><div className="capture-heading"><h2>Ουρά συγχρονισμού <span>{drafts.length}</span></h2><p>{drafts.length?'Οι παρακάτω καταγραφές είναι αποθηκευμένες μόνο σε αυτή τη συσκευή μέχρι να επιβεβαιώσει ο server.':'Καμία εκκρεμής καταγραφή σε αυτή τη συσκευή.'}</p></div>{!!drafts.length&&<div className="capture-actions"><button className="wk-button" onClick={()=>void sync()}>Συγχρονισμός τώρα</button><button className="wk-button" onClick={()=>download(JSON.stringify(drafts.map(({image,...d})=>d),null,2),'leaksy-pending-records.json')}>Αντίγραφο εκκρεμοτήτων (χωρίς εικόνες)</button></div>}{drafts.map(d=><div className="capture-draft" key={d.id}><code>{d.code}</code><strong>{money(d.cents)}</strong><span>{d.state==='error'?d.error:'Αναμονή συγχρονισμού'}</span><button className="wk-button" onClick={()=>void retryDraft(d.id,owner).then(sync)}>Επανάληψη</button><button className="wk-button" onClick={()=>{if(confirm('Να διαγραφεί μόνο αυτή η μη συγχρονισμένη καταγραφή;'))void discardDraft(d.id,owner)}}>Διαγραφή</button></div>)}</section>
  </div>
}
