import { describe,it,expect,vi } from 'vitest'
import { buildBundle,decide,callJev,dateValue,validGtin,validateInput,ENDPOINT,MODEL,type CaptureInput,type Product,type Bundle } from '../../supabase/functions/lixi-jev/core'
const item:Product={id:'00000000-0000-4000-8000-000000000003',internal_code:'0036197',barcode:'5201050130807',description:'ΜΟΥΣΤΑΡΔΑ ΑΠΑΛΗ 250 ΓΡ',unit:'Τεμάχιο',updated_at:'2026-09-20T00:00:00Z',catalog_price:1.46}
function input(...texts:string[]):CaptureInput{return{id:'00000000-0000-4000-8000-000000000001',storeId:'00000000-0000-4000-8000-000000000002',observedAt:'2026-09-22T08:00:00Z',imageHash:'a'.repeat(64),evidencePath:'test.jpg',barcodes:[{text:'5201050130807',format:'EAN13'}],ocr:{engine:'PP-OCRv5',width:1000,height:800,elapsedMs:250,lines:texts.map((text,i)=>({text,score:.999,box:{x:10,y:i*100,width:500,height:30}}))}}}
function answers(b:Bundle,override:Record<string,string>={}){return{model:MODEL,answers:Object.fromEntries(Object.entries(b.questions).map(([name,q])=>{if(q.type==='noul')return[name,{type:'noul',noul:.9999}];const selected=override[name]??Object.keys(q.criteria).find(k=>k!=='none')??'none';return[name,{type:'choice',choice:selected,confidence:.999,probabilities:Object.fromEntries(Object.keys(q.criteria).map(k=>[k,k===selected?1:0]))}]}))}}
describe('Jev evidence policy',()=>{
 it('validates an input without sharing its image bytes with Jev',()=>expect(validateInput(input('1,95 €')).imageHash).toHaveLength(64))
 it('rejects oversized OCR input',()=>expect(()=>validateInput({...input(),ocr:{...input().ocr,lines:Array(201).fill(input('x').ocr.lines[0])}})).toThrow())
 it('checks EAN checksum',()=>{expect(validGtin('5201050130807')).toBe(true);expect(validGtin('5201050130808')).toBe(false)})
 it('rejects impossible dates rather than changing them to month end',()=>{expect(dateValue('31/02/2027')).toBeNull();expect(dateValue('20/10/26')).toBe('2026-10-20')})
 it('builds observed price and expiry candidates',()=>{const b=buildBundle(input('0036197','1,95 €','ΛΗΞΗ 20/10/2026'),[item]);expect(Object.values(b.prices)[0].value).toBe(195);expect(Object.values(b.dates)[0].value.iso).toBe('2026-10-20')})
 it('automatically approves an exact supported product price and date',()=>{const b=buildBundle(input('0036197','1,95 €','ΛΗΞΗ 20/10/2026'),[item]);expect(decide(b,answers(b))).toMatchObject({status:'approved',plan:{product_id:item.id,price_cents:195,expiry_date:'2026-10-20'}})})
 it('does not mistake a unit price for the shelf selling price',()=>{const b=buildBundle(input('7,80 €/KG'),[item]);expect(Object.keys(b.prices)).toHaveLength(0);expect(decide(b,answers(b)).status).toBe('review')})
 it('does not invent a missing expiry date',()=>{const b=buildBundle(input('1,95 €'),[item]);expect(decide(b,answers(b)).plan?.expiry_date).toBeNull()})
 it('does not automatically approve an unlabelled date',()=>{const b=buildBundle(input('20/10/2026'),[item]);expect(decide(b,answers(b)).reasons).toContain('unknown_date_kind')})
 it('rejects an unknown product choice from the provider',()=>{const b=buildBundle(input('1,95 €'),[item]);expect(decide(b,answers(b,{product:'invented_product'})).status).toBe('review')})
 it('rejects low OCR confidence despite confident model output',()=>{const i=input('1,95 €');i.ocr.lines[0].score=.5;const b=buildBundle(i,[item]);expect(decide(b,answers(b)).reasons).toContain('low_ocr_price')})
 it('quarantines multi-product captures',()=>{const i=input('0036197','0036198','1,95 €');const b=buildBundle(i,[item,{...item,id:'other',internal_code:'0036198'}]);expect(decide(b,answers(b)).reasons).toContain('multiple_products')})
 it('does not map an unobserved new store code from a barcode',()=>{const b=buildBundle(input('ΜΟΥΣΤΑΡΔΑ','1,95 €'),[]);expect(Object.keys(b.items)).toHaveLength(0)})
 it('proposes new records only with observed code unit description and decoded GTIN',()=>{const b=buildBundle(input('0036197','ΜΟΥΣΤΑΡΔΑ ΑΠΑΛΗ','Τεμάχιο','1,95 €'),[]);expect(Object.values(b.items).some(p=>p.new_product&&p.internal_code==='0036197')).toBe(true)})
 it('quarantines large price changes',()=>{const b=buildBundle(input('99,95 €'),[item]);expect(decide(b,answers(b)).reasons).toContain('large_price_change')})
 it('rejects malformed probability distributions',()=>{const b=buildBundle(input('1,95 €'),[item]),a=answers(b);(a.answers.product as any).probabilities={none:0};expect(decide(b,a).status).toBe('review')})
 it('calls only the OpenRouter Decisions endpoint with typed questions',async()=>{const b=buildBundle(input('1,95 €'),[item]);const fn=vi.fn().mockResolvedValue(new Response(JSON.stringify(answers(b)),{status:200}));const r=await callJev(b,'test-placeholder-not-a-secret',fn as any);expect(r.decision.status).toBe('approved');expect(fn.mock.calls[0][0]).toBe(ENDPOINT);expect(JSON.parse(fn.mock.calls[0][1].body)).toMatchObject({model:MODEL,questions:{price:{type:'choice'}}});expect(fn.mock.calls[0][1].body).not.toContain('messages')})
 it('does not silently fall back to chat completions',async()=>{const b=buildBundle(input('1,95 €'),[item]);const fn=vi.fn().mockResolvedValue(new Response('{}',{status:404}));await expect(callJev(b,'test',fn as any)).rejects.toThrow('provider_http_404');expect(fn).toHaveBeenCalledTimes(1)})
 it('does not send a request when no key is configured',async()=>{const fn=vi.fn();await expect(callJev(buildBundle(input(),[item]),'',fn as any)).rejects.toThrow('provider_not_configured');expect(fn).not.toHaveBeenCalled()})
})
